# Generated by Django 5.2 on 2025-08-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Nascimento'),
        ),
    ]
