# Generated by Django 5.2 on 2025-08-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Paciente')),
                ('date', models.DateTimeField(verbose_name='Data da Consulta')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição da Consulta')),
                ('duration', models.IntegerField(default=30)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-date'],
            },
        ),
    ]
