# Generated by Django 5.2 on 2025-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descrição da Consulta'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
