# Generated by Django 5.2 on 2025-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Endereço do Responsável'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email do Responsável'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, verbose_name='Gênero do Responsável'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefone do Responsável'),
        ),
    ]
