# Generated by Django 5.2.5 on 2025-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Médico')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, verbose_name='Gênero do Médico')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone do Médico')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Médico')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço do Médico')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF do Médico')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['name'],
            },
        ),
    ]
